version: "3.8"

services:
  app:
    image: kirito140/test_myapp:latest
    container_name: demo-app
    ports:
    - "2005:2005"
    depends_on:
    - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  db:
    image: kirito140/demo-mysql:latest
    container_name: demo-mysql
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
    - "3307:3306"
    volumes:
    - db_data:/var/lib/mysql

volumes:
  db_data:
