version: "3.8"

services:
  app:
    image: kirito140/test_myapp:latest
    container_name: demo-app
    ports:
      - "2005:2005"
    volumes:
      - ./src/main/resources/application.yml:/app/application.yml:ro
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/demo
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: ${MDP} # <<< utilise la syntaxe Docker Compose, pas $(mdp)

  db:
    image: kirito140/demo-mysql:latest

    container_name: demo-mysql
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: admin
      MYSQL_PASSWORD: ${MDP}
      MYSQL_ROOT_PASSWORD: ${MDP}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: