version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
    container_name: demo-app
    ports:
      - "2005:2005"
    volumes:
      - ./src/main/resources/application.yml:/app/application.yml:ro
    depends_on:
      - db
    environment:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

  db:
    build:
      context: .
      dockerfile: dockerfil-mysql.dockerfile
    container_name: demo-mysql
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
