version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile   # <<< nom corrigé
    container_name: demo-app
    ports:
      - "2005:2005"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  db:
    build:
      context: .
      dockerfile: dockerfil-mysql.dockerfile
    container_name: demo-mysql
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
