# Exemple de configuration Spring Boot pour ce projet
server:
  port: 2005

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

# Autres propriétés personnalisées ici
