name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  tst-exe:
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.USERNAME }}
      DB_PASSWORD: ${{ secrets.MDP }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "24"

      - name: Build JAR
        run: mvn clean package

      - name: Run Docker containers
        run: docker compose up -d

      - name: Verify application is running
        run: |
          echo "⏳ Attente du démarrage de l'application..."
          sleep 30
          echo "🔍 Vérification sur http://localhost:2005"
          if ! curl -f http://localhost:2005; then
            echo "❌ L'application n'a pas démarré correctement. Logs :"
            docker compose logs
            exit 1
          fi

      - name: Stop Docker containers
        if: always()
        run: docker compose down

  build-demo:
    runs-on: ubuntu-latest
    needs: tst-exe

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.USERNAME }}
      DB_PASSWORD: ${{ secrets.MDP }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "24"

      - name: Build JAR
        run: mvn clean package

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: kirito140/test_myapp
          tags: v1, latest
          registry: docker.io
          dockerfile: dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build-db:
    runs-on: ubuntu-latest
    needs: tst-exe
    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.USERNAME }}
      DB_PASSWORD: ${{ secrets.MDP }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "24"

      - name: Build JAR
        run: mvn clean package

      - name: Run Docker containers
        run: docker build -t demo-mysql -f dockerfile-mysql.dockerfile .

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: kirito140/test_mysql
          tags: v1, latest
          registry: docker.io
          dockerfile: dockerfile-mysql.dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
